### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by Chebol1951** [ZeeZide/Battery-Status-for-HomeMatic#13]
the battery values were initially displayed. After approx. 2 weeks of use, only a few battery statuses are displayed.,

**Comment by helje5** [comment]
Maybe one of the recent updates broke something. Do you know which type of devices have gone missing? (is it a specific type, or arbitrary devices?)

P.S.: Deutsch ist hier auch OK, wenn das angenehmer sein sollte :-)

**Comment by Chebol1951** [comment]
Vielen Dank für das Angebot. Ich verwende zwei CCU2 an verschiedenen Standorten. An beiden Standorten sind HM sowie HMIP Teilnehmer verbaut. Zu Beginn konnte ich an fast allen Teilnehmern den Ladungsstand in Volt der Batterien ablesen. Aktuell wird an einem Standort Spannungswerte bei allen IP Teilnehmern sowie Thermostate Typ HM-CT-RT-DN angezeigt. Jedoch bei allen Sensoren Typ HM-SEC-SC-2, HM-SEC-RHS, HM-WDQ0202707, HM-SEC-SD  sowie HM-SEN-MDIR-O-3 kann ich den Ladezustand der jeweiligen Batterie nur an den Balken im Batteriesymbol abschätzen. Am zweiten Standort ist das Bild ähnlich auch wenn andere reine HM Aktoren verbaut sind.

 

Vielen Dank für Ihre Stellungsnehme.

Besten Gruß

Walter Hegel


 
 

Gesendet: Donnerstag, 04. März 2021 um 17:34 Uhr
Von: "Helge Heß" <notifications@github.com>
An: "ZeeZide/Battery-Status-for-HomeMatic" <Battery-Status-for-HomeMatic@noreply.github.com>
Cc: "Chebol1951" <marderbiss@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ZeeZide/Battery-Status-for-HomeMatic] Missing values (#13)


 

Maybe one of the recent updates broke something. Do you know which type of devices have gone missing? (is it a specific type, or arbitrary devices?)

P.S.: Deutsch ist hier auch OK, wenn das angenehmer sein sollte :-)

**Comment by helje5** [comment]
Ich habe mir die Geräte gerade noch einmal angeschaut.

- HM-SEC-SC, HM-SEC-RHS und  HM-SEC-SD habe ich selbst auch, diese Sensoren liefern keine Volt-Werte, nur den `LOWBAT` Status (also ob die Batterien leer sind). (Im übrigen übertragen Geräte mit kleinen Batterien den Batteriestand meist nur bei Benutzung).
- Einen HM-SEN-MDIR-O habe ich nicht, aber einen HM-SEC-MDIR. Dieser übermittelt ebenfalls keine Spannungswerte. Ich gehe davon aus, dass das beim HM-SEN-MDIR-O identisch ist.
- HM-WDQ0202707 kenne ich nicht, und finde ich auch im Internet nicht, was ist das für ein Gerät? Ich habe eine HM-WDS100-C6-O (die Wetterstation), diese überträgt aber ebenfalls keine Spannung.

HM-CT-RT-DN ist an meinen beiden Locations auch tatsächlich der einzige HomeMatic Sensor der Batteriespannungswerte überträgt. Bei HM-IP gibt es etwas mehr Geräte die diese Werte übertragen.

Falls das für Sie interessant sein sollte, die verfügbaren Datenpunkte von den meisten HM Geräten findet man hier: [HomeMatic-Script Dokumentation, Teil 4: Datenpunkte](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf) als PDF Dokumentation von eq-3.

**Comment by Chebol1951** [comment]
Hallo Frau Heß,vielen lieben Dank für die ausführliche Antwort. Alles klar, irgendwie dachte ich die Spannungswerte gesehen zu haben. Bei der Eingabe von HM-WDQ0202707   muss ich wohl in der Zeile verrutscht sein. Sorry. Gemeint ist der   HM-WDS10-TH-O, der ein Temperatur und Feuchtesensor ist für den Außenbereich. Vermute er wird dann auch nur den Status „Lowbat“ senden.Besten Dank für Ihre Mühe, bleiben Sie gesund. Mit besten Gruß Walter Hegel Gesendet mit der WEB.DE iPad AppAm 09.03.21 um 13:13 schrieb Helge Heß
                
            
            
                
                    Von: "Helge Heß" <notifications@github.com>Datum: 9. März 2021An: "ZeeZide/Battery-Status-for-HomeMatic" <Battery-Status-for-HomeMatic@noreply.github.com>Cc: "Chebol1951" <marderbiss@web.de>,"Author" <author@noreply.github.com>Betreff: Re: [ZeeZide/Battery-Status-for-HomeMatic] Missing values (#13)
                
                

Ich habe mir die Geräte gerade noch einmal angeschaut.



HM-SEC-SC, HM-SEC-RHS und  HM-SEC-SD habe ich selbst auch, diese Sensoren liefern keine Volt-Werte, nur den LOWBAT Status (also ob die Batterien leer sind). (Im übrigen übertragen Geräte mit kleinen Batterien den Batteriestand meist nur bei Benutzung).

Einen HM-SEN-MDIR-O habe ich nicht, aber einen HM-SEC-MDIR. Dieser übermittelt ebenfalls keine Spannungswerte. Ich gehe davon aus, dass das beim HM-SEN-MDIR-O identisch ist.

HM-WDQ0202707 kenne ich nicht, und finde ich auch im Internet nicht, was ist das für ein Gerät? Ich habe eine HM-WDS100-C6-O (die Wetterstation), diese überträgt aber ebenfalls keine Spannung.



HM-CT-RT-DN ist an meinen beiden Locations auch tatsächlich der einzige HomeMatic Sensor der Batteriespannungswerte überträgt. Bei HM-IP gibt es etwas mehr Geräte die diese Werte übertragen.

Falls das für Sie interessant sein sollte, die verfügbaren Datenpunkte von den meisten HM Geräten findet man hier: HomeMatic-Script Dokumentation, Teil 4: Datenpunkte als PDF Dokumentation von eq-3.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ZeeZide/Battery-Status-for-HomeMatic/issues/13#issuecomment-793797765",

"url": "https://github.com/ZeeZide/Battery-Status-for-HomeMatic/issues/13#issuecomment-793797765",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by helje5** [comment]
> Hallo Frau Heß,vielen lieben Dank für die ausführliche Antwort. 

Ich bin eigentlich gar keine Frau, aber wer weiss wie ich mich noch so orientiere 😀 (kein Problem, kommt häufiger vor)

> Alles klar, irgendwie dachte ich die Spannungswerte gesehen zu haben. Bei der Eingabe von HM-WDQ0202707   muss ich wohl in der Zeile verrutscht sein. Sorry. Gemeint ist der   HM-WDS10-TH-O, der ein Temperatur und Feuchtesensor ist für den Außenbereich. Vermute er wird dann auch nur den Status „Lowbat“ senden.Besten Dank für Ihre Mühe, bleiben Sie gesund. Mit besten Gruß Walter Hegel

HM-WDS10-TH-O habe ich selbst auch, der liefert wie viele andere HM Geräte nur den Lowbat. Alles was Batterie betrieben ist, versucht Funken zu aktuellen Werte wie Spannung zu vermeiden (um selbst Batterie zu sparen).

Ich schliesse dieses Problem dann erstmal, ich denke nicht dass da vorher was angezeigt wurde was gar nicht von den Geräten geliefert wurde. Trotzdem vielen Dank für den Aufwand einen Bug-Report überhaupt zu erstellen, ich weiss das zu schätzen. Anders kann Software nicht besser werden.

**Comment by Chebol1951** [comment]
Sorry Herr Heß,habe eine gute „Ausrede“ 🤓, meine Cousine heißt auch Helge daher möglicherweise meine unüberlegte Annahme.  Sorry. Dank für die Aufklärung und bleiben Sie gesund. 😊Besten Gruß Walter Hegel Gesendet mit der WEB.DE iPad AppAm 09.03.21 um 23:24 schrieb Helge Heß
                
            
            
                
                    Von: "Helge Heß" <notifications@github.com>Datum: 9. März 2021An: "ZeeZide/Battery-Status-for-HomeMatic" <Battery-Status-for-HomeMatic@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"Chebol1951" <marderbiss@web.de>Betreff: Re: [ZeeZide/Battery-Status-for-HomeMatic] Missing values (#13)
                
                



Hallo Frau Heß,vielen lieben Dank für die ausführliche Antwort.



Ich bin eigentlich gar keine Frau, aber wer weiss wie ich mich noch so orientiere 😀 (kein Problem, kommt häufiger vor)



Alles klar, irgendwie dachte ich die Spannungswerte gesehen zu haben. Bei der Eingabe von HM-WDQ0202707   muss ich wohl in der Zeile verrutscht sein. Sorry. Gemeint ist der   HM-WDS10-TH-O, der ein Temperatur und Feuchtesensor ist für den Außenbereich. Vermute er wird dann auch nur den Status „Lowbat“ senden.Besten Dank für Ihre Mühe, bleiben Sie gesund. Mit besten Gruß Walter Hegel



HM-WDS10-TH-O habe ich selbst auch, der liefert wie viele andere HM Geräte nur den Lowbat. Alles was Batterie betrieben ist, versucht Funken zu aktuellen Werte wie Spannung zu vermeiden (um selbst Batterie zu sparen).

Ich schliesse dieses Problem dann erstmal, ich denke nicht dass da vorher was angezeigt wurde was gar nicht von den Geräten geliefert wurde. Trotzdem vielen Dank für den Aufwand einen Bug-Report überhaupt zu erstellen, ich weiss das zu schätzen. Anders kann Software nicht besser werden.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ZeeZide/Battery-Status-for-HomeMatic/issues/13#issuecomment-794536544",

"url": "https://github.com/ZeeZide/Battery-Status-for-HomeMatic/issues/13#issuecomment-794536544",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
