### ISSUE TITLE
Traking battery change not possible for HM-SEN-MDIR-WM55

### ISSUE THREAD

**Issue by gerklu** [ZeeZide/Battery-Status-for-HomeMatic#14]
Traking battery change is not possible for device type HM-SEN-MDIR-WM55.

![6E03C9E4-36A3-4096-B1AE-01728857704E](https://user-images.githubusercontent.com/24853678/164894613-f93ef140-7c89-493c-8f3e-c6c424a832c8.jpeg)

**Comment by helje5** [comment]
Prima, danke! Ist gefixt und kommt dann mit dem nächsten Update.

**Comment by helje5** [comment]
Da war ich leicht verwirrt, ich hatte den als Batteriegerät in 1.0.56 entfernt, aber er ist ja ein Batterie betriebenes Gerät (2x AAA). Fix kommt.

https://de.elv.com/elv-homematic-komplettbausatz-funk-bewegungsmelder-mit-taster-fuer-55er-rahmen-hm-sen-mdir-wm55-fuer-smart-home-hausautomation-140848

**Comment by helje5** [comment]
Kommt in 1.0.58.
