### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by cactus-online** [ZeeZide/Battery-Status-for-HomeMatic#15]
CCU is well configured (same settings like e.g. @Home app). DNS name is resolvable (using IPv4 IP instead doesn't change anything). Secure connection is enabled. CCU (Raspberrymatic 3.69.7.20230626) is using a self signed certificate. Login credentials  (Admin) copied from password safe (and typed manually). Remote Homematic-Script API configured with full access. Battery Status for Homematic app can't access. Rega API test in Browser with sucess. Is there any change for debugging the issue ?

**Comment by helje5** [comment]
Was ist denn der genau Fehler den die App ausgibt? Nachdem man das TLS Zertifikat im Safari aktiviert hat, sollte es an sich gehen.

**Comment by cactus-online** [comment]
Das Zertifikat habe ich dem Safari erlaubt. Der Rega Api Zugriff( https port 48181, http port 8181) funktioniert ohne weiteres Gemeckere.

Die App meldet "Die Basisstation (CCU) ist nicht erreichbar, Login oder Passwort sind falsch. Zugriff [...] Die CCU erfordert eine sichere Verbindung".


Letzteres ist etwas irritierend, denn in den Einstellungen ist "Sichere Verbindung verwenden" an.

**Comment by helje5** [comment]
Soweit ich das sehen kann wird "Die CCU erfordert eine sichere Verbindung" nur als ein Beispiel (zusammen mit 3 anderen) ausgegeben, warum die Verbindung möglicherweise nicht klappt.
Vlt doch Login/Passwort falsch, Gross-/Kleinschreibung eventl?

**Comment by cactus-online** [comment]
Fehler im Hostnamen, verstecktes Zeichen … . Danke.

**Comment by helje5** [comment]
Etwas das ich durch mehr Überprüfung besser machen könnte? Extra Leerzeichen oder sowas?

**Comment by cactus-online** [comment]
Durch das viele Hin- und Her lässt sich das nicht mit Gewissheit sagen. Letztlich musste ich feststellen, dass es bei mir nur via IPv4 IP geht, nicht mit dem Hostnamen, der ansonsten aber auf dem Handy aufgelöst werden kann. Auch gab es ein Issue mit dem Usernamen (Leerzeichen am Ende). Die Fehlermeldung könnte spezifischer sein, dass würde helfen. Aber am Ende ist für mich alles geklärt und läuft. Dankeschön.

Manche Devices fühlen sich als Batterie-Devices, sind es aber bei mir nicht. Die ausblenden zu können wäre schön, hat aber nichts mit diesem Issue zu tun.

**Comment by helje5** [comment]
> Manche Devices fühlen sich als Batterie-Devices, sind es aber bei mir nicht

Wenn möglich, bitte die Typen schicken die falsch als Batteriegeräte angezeigt werden, ich korrigiere das dann.

**Comment by bottkars** [comment]
Habe das gleiche problem wi @cactus-online . ccu3 lässt sich nicht über Hostnamen ansprechen ..... browsertest/tcl geht aber geht aber. ist evtl längenbegrenzung im domainname?  habe xxxx.yyyy.ddddddddd.rrr ( redacted ) als hostname

**Comment by helje5** [comment]
Es gibt da keinerlei künstliche Beschränkung beim Hostnamen, wenn der Zugriff im Safari klappt, sollte er definitiv auch in der App klappen.
Mit der IP-Adresse klappt es?
