### ISSUE TITLE
Thermostat groups show up as battery powered devices

### ISSUE THREAD

**Issue by helje5** [ZeeZide/Battery-Status-for-HomeMatic#9]
Need to figure out how to create & detect them.

**Comment by cptnnm** [comment]
After I bought the software I stumbled across this bug. It would be nice if this behavior can be fixed. Could it be a solution to filter out the devices starting with INT?

![image](https://user-images.githubusercontent.com/3016212/139746965-b5e11ac6-75d2-4160-a4d9-cfb2283b6e90.jpeg)

**Comment by helje5** [comment]
Yes, HmIP heating groups are going to be filtered out in the next update, likely coming end of the week.

**Comment by cptnnm** [comment]
Thanks for the update. It works as expected. 👍
